name: GitHub Actions Demo

on:
  push:
    branches: main
    paths-ignore: .github
  pull_request:
    branches: main
  
  schedule:
    - cron: '15 6 * * 0'
    
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
    
jobs: 
    Build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up environment variables
          run: |
            echo "EVENT_NAME=${{ github.event_name }}" >> $GITHUB_ENV
            echo "BRANCH_NAME=${{ github.ref }}" >> $GITHUB_ENV

      #  - name: Output event name
      #    run: echo "Event name: ${{ env.EVENT_NAME }}"

      #  - name: Output branch name
      #    run: echo "Branch name: $BRANCH_NAME"

        - name: List repository files
          run:  |
            echo "The repository ${{ github.repository }} contains the following files:"
            tree
    Test:
      runs-on: ubuntu-latest
      if: github.event_name == 'workflow_dispatch'
      needs: Build
      environment: Test
      steps:
        - run: echo "🧪 Testing..."

    Load-Test:
      runs-on: ubuntu-latest
      if: github.event_name == 'workflow_dispatch'
      needs: Build
      environment: Load-Test
      steps:
        - run: |
            echo "🧪 Testing..."
            sleep 15

    Production:
      runs-on: ubuntu-latest
      needs: [Test, Load-Test]
      environment:
        name: Production
        url: https://writeabout.net
      if: github.event.inputs.environment == 'Production'
      steps:
        - run: |
            echo "🚀 Step 1..."
            sleep 10
        - run: |
            echo "🚀 Step 2..."
            sleep 10
        - run: |
            echo "🚀 Step 3..."
            sleep 10
        - run: |
            echo "🚀 Step 4..."
            sleep 10
        - run: |
            echo "🚀 Step 5..."
            sleep 10
