name: GitHub Actions Demo

on:
  push:
    branches: main
    paths-ignore: .github
  pull_request:
    branches: main
  
  schedule:
    - cron: '15 6 * * 0'
    
  workflow_dispatch:
    
jobs: 
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up environment variables
          run: |
            echo "EVENT_NAME=${{ github.event_name }}" >> $GITHUB_ENV
            echo "BRANCH_NAME=${{ github.ref }}" >> $GITHUB_ENV

      #  - name: Output event name
      #    run: echo "Event name: ${{ env.EVENT_NAME }}"

      #  - name: Output branch name
      #    run: echo "Branch name: $BRANCH_NAME"

        - name: List repository files
          run: ls -R $GITHUB_WORKSPACE
   
  
